# Generated by Django 3.1.6 on 2021-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
